blank_issues_enabled: true
contact_links:
  - name: Al3omda Support
    url: https://t.me/GROUP_VEGA
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://t.me/GROUP_VEGA
    about: Documentation for getting started with bot.
